# This is a basic workflow to help you get started with Actions

name: Bridgecrew - Prisma Cloud

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: 
  contents: read
  issues: write
  pull-requests: write

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Bridgecrew-Prisma-Cloud:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run Bridgecrew
        #if: github.event_name == 'pull_request'
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-action@master 
        env:
          PRISMA_API_URL: https://api.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          soft_fail: true
          #directory: api
          #file: terraform/bad-s3.tf
